invApp/urls.py
from django.urls import path
from . import views
#app name
app_name = 'invApp'
#views/path routes

urlpatterns = [
    path('', views.home_view, name='home'),
    path('create/', views.product_create_view, name='product_create'),
    path('list', views.product_list_view, name='product_list'),
    path('update/<int:product_id>/', views.update_confirm_view, name='product_update'),
    path('delete/<int:product_id>/', views.product_delete_view, name='product_delete'),
    path('delete/<int:product_id>/', views.delete_success_view, name='delete_success'),
]

invProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('invApp.urls'))
]

invApp/models.py
from django.db import models

# Create your models here.
#Product table
class Product(models.Model):
  product_id = models.AutoField(primary_key=True)
  product_name = models.CharField(max_length=100)
  sku = models.CharField(max_length=50, unique=True)
  price = models.FloatField()
  quantity = models.IntegerField()
  supplier = models.CharField(max_length=100)
  
  def __str__(self):
    return self.product_name

invApp/forms.py
from django import forms
from .models import Product


#create the form
class ProductForm(forms.ModelForm):
  class Meta:
    model = Product
    fields ='__all__'
    lables = {
      'product_id':'Product ID',
      'product_name':'Product Name',
      'sku':'SKU',
      'price':'Price',
      'quantity':'Quantity',
      'supplier':'Supplier',
    }
    widgets = {
      'product_id':forms.NumberInput(attrs={'placeholder':'eg. 1', 'class':'form-control'}),
      'product_name':forms.TextInput(attrs={'placeholder':'eg. Shirt', 'class':'form-control'}),
      'sku':forms.TextInput(attrs={'placeholder':'eg. W1234', 'class':'form-control'}),
      'price':forms.NumberInput(attrs={'placeholder':'eg. 25.45', 'class':'form-control'}),
      'quantity':forms.NumberInput(attrs={'placeholder':'eg. 25', 'class':'form-control'}),
      'supplier':forms.TextInput(attrs={'placeholder':'eg. Soko LTD', 'class':'form-control'}),

    }

invApp/views.py
from django.shortcuts import render, redirect
from .forms import ProductForm
from .models import Product


# Create your views here.
#this application is applying CRUD, Create, Read/View, Update, Delete product
#Home View
def home_view(request):
  return render(request, 'invApp/home.html')

#Create View
def product_create_view(request):
  form = ProductForm()
  if request.method == 'POST':
    form = ProductForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('invApp:product_list')
    # else:
    #   form = ProductForm()
  return render(request, 'invApp/product_form.html', { 'form':form })

#Read/View View
def product_list_view(request):
  products = Product.objects.all()
  return render(request, 'invApp/product_list.html', { 'products':products })

def update_confirm_view(request, product_id):
  # product_id = request.GET.get('id')
  product = Product.objects.get(product_id=product_id)
  return render(request, 'invApp/update_confirm.html', { 'product':product })

#Update View
def product_update_view(request, product_id):
  product = Product.objects.get(product_id=product_id)
  form = ProductForm()
  if request.method == "POST":
    form = ProductForm(request.POST, instance=product)
    if form.is_valid():
      form.save()
      return redirect('invApp:product_list')
  return render(request, 'invApp/product_form.html', {'form':form})

#Delete View
def product_delete_view(request, product_id):
  product = Product.objects.get(product_id=product_id)
  if request.method == "POST":
    product.delete()
    return redirect('invApp:delete_success')
  return render(request, 'invApp/product_confirm_delete.html', { 'product':product })
# Delete success
def delete_success_view(request, product_id):
  product = Product.objects.get(product_id=product_id)
  return render(request, 'invApp/delete_success.html', { 'product':product })

invApp/templates/invApp/delete_success.html
{% extends 'invApp/layout.html' %}


{% block title %}
  Product List
{% endblock title %}
  
  {% block navbar %}
  <p class="text-center text-success">
    {{ product.product_name }} Was succsessfuly deleted!
  </p>
  <div class="flex m-2">
    <p class="text-center">Go to Availbale products<a class=" btn btn-warning m-2" href="{% url 'invApp:product_list' %}">Products in Stock</a></p>
    <p class="text-center">Go to Home Page<a class=" btn btn-primary m-2" href="{% url 'invApp:home' %}">Home</a></p>
  </div>

  {% endblock navbar %}

invApp/templates/invApp/home.html
{% extends 'invApp/layout.html' %}


{% block title %} Home {% endblock title %}
  

{% block content %}
  <div class="jumbotron text-center">
    <h1 class="display-4">Welcome to Our Inventory management Sysytem.</h1>
    <p class="lead">Manage your products effectively and effeciently.</p>
    <hr class="my-4">
    <p>User navigation bar to add, view, update or delete product.</p>
    <a href="{% url 'invApp:product_list' %}" class="btn btn-primary btn-lg" role="button">View Products</a>
  </div>
{% endblock content %}
  

invApp/templates/invApp/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
  {% block title %}
    Inventory <Applet></Applet>
  {% endblock title %}
    </title>
    <link href="
https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css
" rel="stylesheet">
</head>
<style>
  body {
    padding-top: 56px;
  }
  .navbar {
    background-color: #343a40;
  }
  .container{
    margin-top: 20px;
  }
  .navbar-brand, .nav-link {
    color: #fff !important;
  }
  .table th, .table td {
    vertical-align: middle;
  }
</style>
<body>
  <!-- navigation menu -->
  {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
      <a href="{% url 'invApp:home' %}" class="navbar-brand">Inventory App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="navbar-item">
            <a href="{% url 'invApp:product_create' %}" class="nav-link">Add Product</a>
          </li>
          <li class="navbar-item">
            <a href="{% url 'invApp:product_list' %}" class="nav-link">Show Products</a>
          </li>
        </ul>
      </div>
    </nav>
  {% endblock navbar %}
    
  <!-- Our body content  -->
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <!-- js link  -->
  <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
  <script src="
https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js
"></script>
</body>
</html>

invApp/templates/invApp/product_confirm_delete.html
{% extends 'invApp/layout.html' %}


{% block title %}
  Product List
{% endblock title %}
  
  {% block content %}
    <h1 class="text-center">Are you sure you want to delete <p class="text-success">{{product.product_name}} ?</p> </h1>
    <p class="text-center">By Clicking <span class="text-danger">Yes</span> You agree to parmanently remove <span class="text-success">{{ product.product_name }} ? </span> from records. Do you agree? </p>
  <form action="" method="post" class="text-center">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes</button>
    <a href="{% url 'invApp:product_list' %}" class="btn btn-secondary">No</a>
  </form>
  {% endblock content %}

invApp/templates/invApp/product_form.html
{% extends 'invApp/layout.html' %}


{% block title %}
  Home
{% endblock title %}
  
  {% block content %}
    <h1 class="text-center">Product Form</h1>
    <form method="POST"class="jumbotron">
      {% csrf_token %}
      {{ form }}
      <div class=" d-flex pt-4 px-5">
        <button type="submit" class="btn btn-primary w-50">Save Product</button>
        <button type="reset" class="btn btn-success w-50 ml-3">Cancel</button>
      </div>
    </form>

    <p class="text-center">Go to Availbale products<a class=" btn btn-warning m-2" href="{% url 'invApp:product_list' %}">Products in Stock</a></p>

  {% endblock content %}
    

invApp/templates/invApp/product_list.html
{% extends 'invApp/layout.html' %}


{% block title %}
  Product List
{% endblock title %}
  
  {% block content %}
    <h1 class="text-center">Product</h1>
    <table class="table table-bordered table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Product ID</th>
          <th>Product Name</th>
          <th>SKU</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Supplier</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        
        {% for product in products %}
          <tr>
            <td>{{ product.product_id }}</td>
            <td>{{ product.product_name }}</td>
            <td>{{ product.sku }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.quantity }}</td>
            <td>{{ product.supplier }}</td>
            <td class="text-center">
              <a href="{% url 'invApp:product_create' %}" class="btn btn-success mx-2">Add</a>
              <a href="{% url 'invApp:product_update' product.product_id %}" class="btn btn-warning">Update</a>
              <a href="{% url 'invApp:product_delete' product.product_id %}" class="btn btn-danger mx-2">Delete</a>
            </td>

          </tr>
        {% endfor %}
          
      </tbody>
    </table>

    <p class="text-center">Go to Home Page<a class=" btn btn-primary m-2" href="{% url 'invApp:home' %}">Home</a></p>
  {% endblock content %}

invApp/templates/invApp/update_confirm.html
{% extends 'invApp/layout.html' %}


{% block title %}
  Update {{ product.product_name }}
{% endblock title %}
  
  {% block content %}
    <p class="text-center">Are you sure you want to Update/Replace <span class="text-success">{{ product.product_name }} ? </span></p>
    <p class="text-center">By Clicking <span class="text-danger">Yes</span> You agree to parmanently remove <span class="text-success">{{ product.product_name }} ? </span> from records. Do you agree? </p>
    <p class="text-center">
      <a href="{% url 'invApp:product_update' product.product_id %}" class="btn btn-danger">Yes</a>
      <a href="{% url 'invApp:product_list' %}" class="btn btn-warning">No</a>
    </p>

    <div class="flex m-2">
      <p class="text-center">Go to Availbale products<a class=" btn btn-warning m-2" href="{% url 'invApp:product_list' %}">Products in Stock</a></p>
      <p class="text-center">Go to Home Page<a class=" btn btn-primary m-2" href="{% url 'invApp:home' %}">Home</a></p>
    </div>
  {% endblock content %}